-- MySQL Script generated by MySQL Workbench
-- Tue Jun 26 17:20:15 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dimelodb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dimelodb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dimelodb` DEFAULT CHARACTER SET utf8 ;
USE `dimelodb` ;

-- -----------------------------------------------------
-- Table `dimelodb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dimelodb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `user` VARCHAR(45) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `photo` VARCHAR(100) NULL,
  `name` TEXT NULL,
  `auth_key` VARCHAR(255) NULL,
  `desc` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `usuario_UNIQUE` (`user` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dimelodb`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dimelodb`.`posts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(45) NOT NULL,
  `from` INT NULL,
  `receiver` INT NOT NULL,
  `anonymous` TINYINT NOT NULL,
  `created_at` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
